import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { router } from 'expo-router';
import React, { useState } from 'react';
import {
  ActivityIndicator,
  Alert,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View
} from 'react-native';

// --- Theme Colors ---
const NEON_GREEN = '#34D399';
const BRIGHT_NEON = '#A7F3D0';
const BACKGROUND_DARK = '#000000';
const CARD_BG = '#111111';
const INPUT_BG = '#1F2937';
const TEXT_LIGHT = '#E5E7EB';
const PLACEHOLDER_COLOR = '#6B7280';

// Supported Options
const LANGUAGES = ['English', 'Urdu', 'Hindi', 'Spanish', 'French'];
const PAGE_COUNTS = ['1 Page', '2 Pages', '3 Pages', '5+ Pages'];

const AIGeneratorScreen = () => {
  const [topicName, setTopicName] = useState('');
  const [language, setLanguage] = useState(LANGUAGES[0]);
  const [pageCount, setPageCount] = useState(PAGE_COUNTS[0]);
  const [isLanguageOpen, setIsLanguageOpen] = useState(false);
  const [isPageCountOpen, setIsPageCountOpen] = useState(false);
  
  // New Loading State
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = () => {
    if (!topicName.trim()) {
      Alert.alert("Error", "Please enter a topic name.");
      return;
    }

    setIsGenerating(true);

    // --- FAKE AI GENERATION LOGIC ---
    // Hum 3 second ka delay dalenge taake user ko lage AI soch raha hai
    setTimeout(() => {
      const dummyContent = generateDummyContent(topicName, language, pageCount);
      
      setIsGenerating(false);
      
      // Navigate to Review Screen with Data
      router.push({
        pathname: '/GeneratedNotesScreen',
        params: { 
          content: dummyContent,
          initialTopic: topicName 
        }
      });
    }, 3000); // 3 seconds delay
  };

  // Helper to create text based on topic (Simulation)
  const generateDummyContent = (topic: string, lang: string, length: string) => {
    return `
# AI Generated Notes: ${topic}
Language: ${lang} | Length: ${length}

## 1. Introduction to ${topic}
${topic} is a fundamental concept that explores the dynamics of the subject. Understanding ${topic} is crucial for mastering advanced theories. This section introduces the core principles and history.

## 2. Key Concepts
- **Principle A:** The building block of ${topic}.
- **Principle B:** How it interacts with the environment.
- **Modern Application:** How we use ${topic} in the year 2025.

## 3. Detailed Analysis
As we dive deeper into ${topic}, we observe interesting patterns. The theoretical framework suggests that when applied correctly, the results are exponential. 

(This is a simulated output for the purpose of the demo. In a real app, this text would come from OpenAI or Gemini API.)

## 4. Conclusion
In conclusion, ${topic} remains a vital area of study. Continuous research and development are expected to reveal more in the coming years.

---
Generated by AI Study Station
    `;
  };

  return (
    <LinearGradient colors={[BACKGROUND_DARK, '#061a12']} style={styles.container}>
      
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()}>
          <Ionicons name="arrow-back-outline" size={30} color={NEON_GREEN} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>AI Notes Generator</Text>
        <Ionicons name="sparkles" size={30} color={NEON_GREEN} />
      </View>

      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>

        {/* Input Section */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>Details Enter Karein</Text>
          <Text style={styles.label}>📝 Topic Name</Text>
          <TextInput
            style={styles.input}
            placeholder="e.g., Quantum Physics Basics"
            placeholderTextColor={PLACEHOLDER_COLOR}
            value={topicName}
            onChangeText={setTopicName}
            editable={!isGenerating} // Disable while generating
          />
        </View>

        {/* Language Section */}
        <View style={styles.card}>
          <Text style={styles.label}>🌐 Choose Language</Text>
          <TouchableOpacity 
            style={styles.dropdownButton} 
            onPress={() => !isGenerating && setIsLanguageOpen(!isLanguageOpen)}
          >
            <Text style={styles.dropdownText}>{language}</Text>
            <Ionicons name={isLanguageOpen ? "chevron-up" : "chevron-down"} size={20} color={NEON_GREEN} />
          </TouchableOpacity>
          {isLanguageOpen && (
            <View style={styles.dropdownOptions}>
              {LANGUAGES.map((lang) => (
                <TouchableOpacity key={lang} style={styles.optionItem} onPress={() => { setLanguage(lang); setIsLanguageOpen(false); }}>
                  <Text style={styles.optionText}>{lang}</Text>
                </TouchableOpacity>
              ))}
            </View>
          )}
        </View>
        
        {/* Page Count Section */}
        <View style={styles.card}>
          <Text style={styles.label}>📄 Content Length</Text>
          <TouchableOpacity 
            style={styles.dropdownButton} 
            onPress={() => !isGenerating && setIsPageCountOpen(!isPageCountOpen)}
          >
            <Text style={styles.dropdownText}>{pageCount}</Text>
            <Ionicons name={isPageCountOpen ? "chevron-up" : "chevron-down"} size={20} color={NEON_GREEN} />
          </TouchableOpacity>
          {isPageCountOpen && (
            <View style={styles.dropdownOptions}>
              {PAGE_COUNTS.map((count) => (
                <TouchableOpacity key={count} style={styles.optionItem} onPress={() => { setPageCount(count); setIsPageCountOpen(false); }}>
                  <Text style={styles.optionText}>{count}</Text>
                </TouchableOpacity>
              ))}
            </View>
          )}
        </View>

        {/* Generate Button with Loader */}
        <TouchableOpacity 
          style={[styles.generateButton, { opacity: isGenerating ? 0.7 : 1 }]} 
          onPress={handleGenerate}
          disabled={isGenerating}
        >
          {isGenerating ? (
            <>
              <ActivityIndicator size="small" color={BACKGROUND_DARK} />
              <Text style={styles.generateButtonText}> Generating...</Text>
            </>
          ) : (
            <>
              <Ionicons name="color-wand-outline" size={28} color="#000" />
              <Text style={styles.generateButtonText}>Generate Notes</Text>
            </>
          )}
        </TouchableOpacity>

      </ScrollView>
    </LinearGradient>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, paddingTop: 60 },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 40 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, marginBottom: 30 },
  headerTitle: { fontSize: 24, fontWeight: 'bold', color: BRIGHT_NEON },
  card: { backgroundColor: CARD_BG, borderRadius: 18, padding: 20, marginBottom: 20, borderWidth: 1, borderColor: '#222' },
  cardTitle: { fontSize: 18, fontWeight: 'bold', color: NEON_GREEN, marginBottom: 20, textAlign: 'center', borderBottomWidth: 1, borderBottomColor: '#333', paddingBottom: 10 },
  label: { fontSize: 16, color: TEXT_LIGHT, fontWeight: '600', marginBottom: 8 },
  input: { width: '100%', backgroundColor: INPUT_BG, color: TEXT_LIGHT, padding: 15, borderRadius: 12, fontSize: 16, borderWidth: 1, borderColor: NEON_GREEN, marginBottom: 10 },
  dropdownButton: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: INPUT_BG, padding: 15, borderRadius: 12, borderWidth: 1, borderColor: NEON_GREEN, marginBottom: 5 },
  dropdownText: { color: TEXT_LIGHT, fontSize: 16 },
  dropdownOptions: { backgroundColor: INPUT_BG, borderRadius: 12, borderWidth: 1, borderColor: NEON_GREEN, maxHeight: 200, overflow: 'hidden' },
  optionItem: { padding: 15, borderBottomWidth: 1, borderBottomColor: '#222' },
  optionText: { color: TEXT_LIGHT, fontSize: 16 },
  generateButton: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', backgroundColor: NEON_GREEN, paddingVertical: 18, borderRadius: 15, marginTop: 30, gap: 10, shadowColor: NEON_GREEN, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.8, shadowRadius: 15, elevation: 15 },
  generateButtonText: { fontSize: 20, fontWeight: '900', color: BACKGROUND_DARK },
});

export default AIGeneratorScreen;
